//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLIndexManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SQLIndexManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDate.
        /// </summary>
        internal static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databases.
        /// </summary>
        internal static string DatabaseBoxTitle {
            get {
                return ResourceManager.GetString("DatabaseBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseId.
        /// </summary>
        internal static string DatabaseId {
            get {
                return ResourceManager.GetString("DatabaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseName.
        /// </summary>
        internal static string DatabaseName {
            get {
                return ResourceManager.GetString("DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataCompression.
        /// </summary>
        internal static string DataCompression {
            get {
                return ResourceManager.GetString("DataCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataFreeSize.
        /// </summary>
        internal static string DataFreeSize {
            get {
                return ResourceManager.GetString("DataFreeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to master.
        /// </summary>
        internal static string DatamaseMaster {
            get {
                return ResourceManager.GetString("DatamaseMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSize.
        /// </summary>
        internal static string DataSize {
            get {
                return ResourceManager.GetString("DataSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataUsedSize.
        /// </summary>
        internal static string DataUsedSize {
            get {
                return ResourceManager.GetString("DataUsedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition.
        /// </summary>
        internal static string Edition {
            get {
                return ResourceManager.GetString("Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileGroupName.
        /// </summary>
        internal static string FileGroupName {
            get {
                return ResourceManager.GetString("FileGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FillFactorValue.
        /// </summary>
        internal static string FillFactor {
            get {
                return ResourceManager.GetString("FillFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix.
        /// </summary>
        internal static string Fix {
            get {
                return ResourceManager.GetString("Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FixType.
        /// </summary>
        internal static string FixType {
            get {
                return ResourceManager.GetString("FixType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragmentation.
        /// </summary>
        internal static string Fragmentation {
            get {
                return ResourceManager.GetString("Fragmentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.github.com/sergiisyrovatchenko/SQLIndexManager.
        /// </summary>
        internal static string GitHubLink {
            get {
                return ResourceManager.GetString("GitHubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconAbout {
            get {
                object obj = ResourceManager.GetObject("IconAbout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconCopy {
            get {
                object obj = ResourceManager.GetObject("IconCopy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconCopyFix {
            get {
                object obj = ResourceManager.GetObject("IconCopyFix", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconDatabases {
            get {
                object obj = ResourceManager.GetObject("IconDatabases", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconDelay {
            get {
                object obj = ResourceManager.GetObject("IconDelay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconElapsedTime {
            get {
                object obj = ResourceManager.GetObject("IconElapsedTime", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconError {
            get {
                object obj = ResourceManager.GetObject("IconError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconErrors {
            get {
                object obj = ResourceManager.GetObject("IconErrors", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconExclude {
            get {
                object obj = ResourceManager.GetObject("IconExclude", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconFilter {
            get {
                object obj = ResourceManager.GetObject("IconFilter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconFix {
            get {
                object obj = ResourceManager.GetObject("IconFix", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconHide {
            get {
                object obj = ResourceManager.GetObject("IconHide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconInclude {
            get {
                object obj = ResourceManager.GetObject("IconInclude", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconIndexes {
            get {
                object obj = ResourceManager.GetObject("IconIndexes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconIndexesSize {
            get {
                object obj = ResourceManager.GetObject("IconIndexesSize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconInfo {
            get {
                object obj = ResourceManager.GetObject("IconInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconLeftCol {
            get {
                object obj = ResourceManager.GetObject("IconLeftCol", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconLog {
            get {
                object obj = ResourceManager.GetObject("IconLog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconNewConnection {
            get {
                object obj = ResourceManager.GetObject("IconNewConnection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconOk {
            get {
                object obj = ResourceManager.GetObject("IconOk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconOptions {
            get {
                object obj = ResourceManager.GetObject("IconOptions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconRefresh {
            get {
                object obj = ResourceManager.GetObject("IconRefresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconReplace {
            get {
                object obj = ResourceManager.GetObject("IconReplace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconRestoreLayout {
            get {
                object obj = ResourceManager.GetObject("IconRestoreLayout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconRun {
            get {
                object obj = ResourceManager.GetObject("IconRun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconSavedSpace {
            get {
                object obj = ResourceManager.GetObject("IconSavedSpace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconScan {
            get {
                object obj = ResourceManager.GetObject("IconScan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconStop {
            get {
                object obj = ResourceManager.GetObject("IconStop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IiconSaveFix {
            get {
                object obj = ResourceManager.GetObject("IiconSaveFix", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncludedColumns.
        /// </summary>
        internal static string IncludedColumns {
            get {
                return ResourceManager.GetString("IncludedColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndexColumns.
        /// </summary>
        internal static string IndexColumns {
            get {
                return ResourceManager.GetString("IndexColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndexID.
        /// </summary>
        internal static string IndexID {
            get {
                return ResourceManager.GetString("IndexID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndexName.
        /// </summary>
        internal static string IndexName {
            get {
                return ResourceManager.GetString("IndexName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndexStats.
        /// </summary>
        internal static string IndexStats {
            get {
                return ResourceManager.GetString("IndexStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndexType.
        /// </summary>
        internal static string IndexType {
            get {
                return ResourceManager.GetString("IndexType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAllowPageLocks.
        /// </summary>
        internal static string IsAllowPageLocks {
            get {
                return ResourceManager.GetString("IsAllowPageLocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsFiltered.
        /// </summary>
        internal static string IsFiltered {
            get {
                return ResourceManager.GetString("IsFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsLob.
        /// </summary>
        internal static string IsLob {
            get {
                return ResourceManager.GetString("IsLob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsLobLegacy.
        /// </summary>
        internal static string IsLobLegacy {
            get {
                return ResourceManager.GetString("IsLobLegacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsNoRecompute.
        /// </summary>
        internal static string IsNoRecompute {
            get {
                return ResourceManager.GetString("IsNoRecompute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsPartitioned.
        /// </summary>
        internal static string IsPartitioned {
            get {
                return ResourceManager.GetString("IsPartitioned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsPK.
        /// </summary>
        internal static string IsPK {
            get {
                return ResourceManager.GetString("IsPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsSparse.
        /// </summary>
        internal static string IsSparse {
            get {
                return ResourceManager.GetString("IsSparse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsSysAdmin.
        /// </summary>
        internal static string IsSysAdmin {
            get {
                return ResourceManager.GetString("IsSysAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsUnique.
        /// </summary>
        internal static string IsUnique {
            get {
                return ResourceManager.GetString("IsUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastRead.
        /// </summary>
        internal static string LastRead {
            get {
                return ResourceManager.GetString("LastRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastWrite.
        /// </summary>
        internal static string LastWrite {
            get {
                return ResourceManager.GetString("LastWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogFreeSize.
        /// </summary>
        internal static string LogFreeSize {
            get {
                return ResourceManager.GetString("LogFreeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogReuseWait.
        /// </summary>
        internal static string LogReuseWait {
            get {
                return ResourceManager.GetString("LogReuseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogSize.
        /// </summary>
        internal static string LogSize {
            get {
                return ResourceManager.GetString("LogSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogUsedSize.
        /// </summary>
        internal static string LogUsedSize {
            get {
                return ResourceManager.GetString("LogUsedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server 2000/2005 is not supported..
        /// </summary>
        internal static string MinVersionMessage {
            get {
                return ResourceManager.GetString("MinVersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyDate.
        /// </summary>
        internal static string ModifyDate {
            get {
                return ResourceManager.GetString("ModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectID.
        /// </summary>
        internal static string ObjectID {
            get {
                return ResourceManager.GetString("ObjectID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectName.
        /// </summary>
        internal static string ObjectName {
            get {
                return ResourceManager.GetString("ObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PagesCount.
        /// </summary>
        internal static string PagesCount {
            get {
                return ResourceManager.GetString("PagesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PagesCountBefore.
        /// </summary>
        internal static string PagesCountBefore {
            get {
                return ResourceManager.GetString("PagesCountBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageSpaceUsed.
        /// </summary>
        internal static string PageSpaceUsed {
            get {
                return ResourceManager.GetString("PageSpaceUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartitionNumber.
        /// </summary>
        internal static string PartitionNumber {
            get {
                return ResourceManager.GetString("PartitionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductLevel.
        /// </summary>
        internal static string ProductLevel {
            get {
                return ResourceManager.GetString("ProductLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductUpdateLevel.
        /// </summary>
        internal static string ProductUpdateLevel {
            get {
                return ResourceManager.GetString("ProductUpdateLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecoveryModel.
        /// </summary>
        internal static string RecoveryModel {
            get {
                return ResourceManager.GetString("RecoveryModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RowsCount.
        /// </summary>
        internal static string RowsCount {
            get {
                return ResourceManager.GetString("RowsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RowsSampled.
        /// </summary>
        internal static string RowsSampled {
            get {
                return ResourceManager.GetString("RowsSampled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SchemaName.
        /// </summary>
        internal static string SchemaName {
            get {
                return ResourceManager.GetString("SchemaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        internal static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerName.
        /// </summary>
        internal static string ServerName {
            get {
                return ResourceManager.GetString("ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerVersion.
        /// </summary>
        internal static string ServerVersion {
            get {
                return ResourceManager.GetString("ServerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatsSampled.
        /// </summary>
        internal static string StatsSampled {
            get {
                return ResourceManager.GetString("StatsSampled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalLookups.
        /// </summary>
        internal static string TotalLookups {
            get {
                return ResourceManager.GetString("TotalLookups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalScans.
        /// </summary>
        internal static string TotalScans {
            get {
                return ResourceManager.GetString("TotalScans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalSeeks.
        /// </summary>
        internal static string TotalSeeks {
            get {
                return ResourceManager.GetString("TotalSeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalUpdates.
        /// </summary>
        internal static string TotalUpdates {
            get {
                return ResourceManager.GetString("TotalUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnusedPagesCount.
        /// </summary>
        internal static string UnusedPagesCount {
            get {
                return ResourceManager.GetString("UnusedPagesCount", resourceCulture);
            }
        }
    }
}
