//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLIndexManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SQLIndexManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseName.
        /// </summary>
        internal static string DatabaseName {
            get {
                return ResourceManager.GetString("DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataCompression.
        /// </summary>
        internal static string DataCompression {
            get {
                return ResourceManager.GetString("DataCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to master.
        /// </summary>
        internal static string DatamaseMaster {
            get {
                return ResourceManager.GetString("DatamaseMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileGroupName.
        /// </summary>
        internal static string FileGroupName {
            get {
                return ResourceManager.GetString("FileGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FillFactorValue.
        /// </summary>
        internal static string FillFactor {
            get {
                return ResourceManager.GetString("FillFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragmentation.
        /// </summary>
        internal static string Fragmentation {
            get {
                return ResourceManager.GetString("Fragmentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndexID.
        /// </summary>
        internal static string IndexID {
            get {
                return ResourceManager.GetString("IndexID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndexName.
        /// </summary>
        internal static string IndexName {
            get {
                return ResourceManager.GetString("IndexName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndexStats.
        /// </summary>
        internal static string IndexStats {
            get {
                return ResourceManager.GetString("IndexStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndexType.
        /// </summary>
        internal static string IndexType {
            get {
                return ResourceManager.GetString("IndexType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAllowPageLocks.
        /// </summary>
        internal static string IsAllowPageLocks {
            get {
                return ResourceManager.GetString("IsAllowPageLocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsFiltered.
        /// </summary>
        internal static string IsFiltered {
            get {
                return ResourceManager.GetString("IsFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsLob.
        /// </summary>
        internal static string IsLob {
            get {
                return ResourceManager.GetString("IsLob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsLobLegacy.
        /// </summary>
        internal static string IsLobLegacy {
            get {
                return ResourceManager.GetString("IsLobLegacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsPartitioned.
        /// </summary>
        internal static string IsPartitioned {
            get {
                return ResourceManager.GetString("IsPartitioned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsPK.
        /// </summary>
        internal static string IsPK {
            get {
                return ResourceManager.GetString("IsPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsSparse.
        /// </summary>
        internal static string IsSparse {
            get {
                return ResourceManager.GetString("IsSparse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsUnique.
        /// </summary>
        internal static string IsUnique {
            get {
                return ResourceManager.GetString("IsUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastUsage.
        /// </summary>
        internal static string LastUsage {
            get {
                return ResourceManager.GetString("LastUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectID.
        /// </summary>
        internal static string ObjectID {
            get {
                return ResourceManager.GetString("ObjectID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectName.
        /// </summary>
        internal static string ObjectName {
            get {
                return ResourceManager.GetString("ObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PagesCount.
        /// </summary>
        internal static string PagesCount {
            get {
                return ResourceManager.GetString("PagesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PagesCountBefore.
        /// </summary>
        internal static string PagesCountBefore {
            get {
                return ResourceManager.GetString("PagesCountBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartitionNumber.
        /// </summary>
        internal static string PartitionNumber {
            get {
                return ResourceManager.GetString("PartitionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RowsCount.
        /// </summary>
        internal static string RowsCount {
            get {
                return ResourceManager.GetString("RowsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SchemaName.
        /// </summary>
        internal static string SchemaName {
            get {
                return ResourceManager.GetString("SchemaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalReads.
        /// </summary>
        internal static string TotalReads {
            get {
                return ResourceManager.GetString("TotalReads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalWrites.
        /// </summary>
        internal static string TotalWrites {
            get {
                return ResourceManager.GetString("TotalWrites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnusedPagesCount.
        /// </summary>
        internal static string UnusedPagesCount {
            get {
                return ResourceManager.GetString("UnusedPagesCount", resourceCulture);
            }
        }
    }
}
